// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: proto/book_author.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorServiceClient is the client API for AuthorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorServiceClient interface {
	CreateAuthor(ctx context.Context, in *CreateAuthorRequest, opts ...grpc.CallOption) (*Author, error)
	CreateAuthorStream(ctx context.Context, opts ...grpc.CallOption) (AuthorService_CreateAuthorStreamClient, error)
	CreateAuthorStreamBidirectional(ctx context.Context, opts ...grpc.CallOption) (AuthorService_CreateAuthorStreamBidirectionalClient, error)
	ListAuthors(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*AuthorList, error)
	GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*Author, error)
}

type authorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorServiceClient(cc grpc.ClientConnInterface) AuthorServiceClient {
	return &authorServiceClient{cc}
}

func (c *authorServiceClient) CreateAuthor(ctx context.Context, in *CreateAuthorRequest, opts ...grpc.CallOption) (*Author, error) {
	out := new(Author)
	err := c.cc.Invoke(ctx, "/pb.AuthorService/CreateAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorServiceClient) CreateAuthorStream(ctx context.Context, opts ...grpc.CallOption) (AuthorService_CreateAuthorStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AuthorService_ServiceDesc.Streams[0], "/pb.AuthorService/CreateAuthorStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &authorServiceCreateAuthorStreamClient{stream}
	return x, nil
}

type AuthorService_CreateAuthorStreamClient interface {
	Send(*CreateAuthorRequest) error
	CloseAndRecv() (*AuthorList, error)
	grpc.ClientStream
}

type authorServiceCreateAuthorStreamClient struct {
	grpc.ClientStream
}

func (x *authorServiceCreateAuthorStreamClient) Send(m *CreateAuthorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *authorServiceCreateAuthorStreamClient) CloseAndRecv() (*AuthorList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AuthorList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authorServiceClient) CreateAuthorStreamBidirectional(ctx context.Context, opts ...grpc.CallOption) (AuthorService_CreateAuthorStreamBidirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &AuthorService_ServiceDesc.Streams[1], "/pb.AuthorService/CreateAuthorStreamBidirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &authorServiceCreateAuthorStreamBidirectionalClient{stream}
	return x, nil
}

type AuthorService_CreateAuthorStreamBidirectionalClient interface {
	Send(*CreateAuthorRequest) error
	Recv() (*Author, error)
	grpc.ClientStream
}

type authorServiceCreateAuthorStreamBidirectionalClient struct {
	grpc.ClientStream
}

func (x *authorServiceCreateAuthorStreamBidirectionalClient) Send(m *CreateAuthorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *authorServiceCreateAuthorStreamBidirectionalClient) Recv() (*Author, error) {
	m := new(Author)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authorServiceClient) ListAuthors(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*AuthorList, error) {
	out := new(AuthorList)
	err := c.cc.Invoke(ctx, "/pb.AuthorService/ListAuthors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorServiceClient) GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*Author, error) {
	out := new(Author)
	err := c.cc.Invoke(ctx, "/pb.AuthorService/GetAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorServiceServer is the server API for AuthorService service.
// All implementations must embed UnimplementedAuthorServiceServer
// for forward compatibility
type AuthorServiceServer interface {
	CreateAuthor(context.Context, *CreateAuthorRequest) (*Author, error)
	CreateAuthorStream(AuthorService_CreateAuthorStreamServer) error
	CreateAuthorStreamBidirectional(AuthorService_CreateAuthorStreamBidirectionalServer) error
	ListAuthors(context.Context, *Blank) (*AuthorList, error)
	GetAuthor(context.Context, *GetAuthorRequest) (*Author, error)
	mustEmbedUnimplementedAuthorServiceServer()
}

// UnimplementedAuthorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorServiceServer struct {
}

func (UnimplementedAuthorServiceServer) CreateAuthor(context.Context, *CreateAuthorRequest) (*Author, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthor not implemented")
}
func (UnimplementedAuthorServiceServer) CreateAuthorStream(AuthorService_CreateAuthorStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateAuthorStream not implemented")
}
func (UnimplementedAuthorServiceServer) CreateAuthorStreamBidirectional(AuthorService_CreateAuthorStreamBidirectionalServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateAuthorStreamBidirectional not implemented")
}
func (UnimplementedAuthorServiceServer) ListAuthors(context.Context, *Blank) (*AuthorList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuthors not implemented")
}
func (UnimplementedAuthorServiceServer) GetAuthor(context.Context, *GetAuthorRequest) (*Author, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthor not implemented")
}
func (UnimplementedAuthorServiceServer) mustEmbedUnimplementedAuthorServiceServer() {}

// UnsafeAuthorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorServiceServer will
// result in compilation errors.
type UnsafeAuthorServiceServer interface {
	mustEmbedUnimplementedAuthorServiceServer()
}

func RegisterAuthorServiceServer(s grpc.ServiceRegistrar, srv AuthorServiceServer) {
	s.RegisterService(&AuthorService_ServiceDesc, srv)
}

func _AuthorService_CreateAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorServiceServer).CreateAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthorService/CreateAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorServiceServer).CreateAuthor(ctx, req.(*CreateAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorService_CreateAuthorStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthorServiceServer).CreateAuthorStream(&authorServiceCreateAuthorStreamServer{stream})
}

type AuthorService_CreateAuthorStreamServer interface {
	SendAndClose(*AuthorList) error
	Recv() (*CreateAuthorRequest, error)
	grpc.ServerStream
}

type authorServiceCreateAuthorStreamServer struct {
	grpc.ServerStream
}

func (x *authorServiceCreateAuthorStreamServer) SendAndClose(m *AuthorList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *authorServiceCreateAuthorStreamServer) Recv() (*CreateAuthorRequest, error) {
	m := new(CreateAuthorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AuthorService_CreateAuthorStreamBidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthorServiceServer).CreateAuthorStreamBidirectional(&authorServiceCreateAuthorStreamBidirectionalServer{stream})
}

type AuthorService_CreateAuthorStreamBidirectionalServer interface {
	Send(*Author) error
	Recv() (*CreateAuthorRequest, error)
	grpc.ServerStream
}

type authorServiceCreateAuthorStreamBidirectionalServer struct {
	grpc.ServerStream
}

func (x *authorServiceCreateAuthorStreamBidirectionalServer) Send(m *Author) error {
	return x.ServerStream.SendMsg(m)
}

func (x *authorServiceCreateAuthorStreamBidirectionalServer) Recv() (*CreateAuthorRequest, error) {
	m := new(CreateAuthorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AuthorService_ListAuthors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorServiceServer).ListAuthors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthorService/ListAuthors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorServiceServer).ListAuthors(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorService_GetAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorServiceServer).GetAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthorService/GetAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorServiceServer).GetAuthor(ctx, req.(*GetAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorService_ServiceDesc is the grpc.ServiceDesc for AuthorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthorService",
	HandlerType: (*AuthorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthor",
			Handler:    _AuthorService_CreateAuthor_Handler,
		},
		{
			MethodName: "ListAuthors",
			Handler:    _AuthorService_ListAuthors_Handler,
		},
		{
			MethodName: "GetAuthor",
			Handler:    _AuthorService_GetAuthor_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateAuthorStream",
			Handler:       _AuthorService_CreateAuthorStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateAuthorStreamBidirectional",
			Handler:       _AuthorService_CreateAuthorStreamBidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/book_author.proto",
}

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error)
	CreateBookStream(ctx context.Context, opts ...grpc.CallOption) (BookService_CreateBookStreamClient, error)
	CreateBookStreamBidirectional(ctx context.Context, opts ...grpc.CallOption) (BookService_CreateBookStreamBidirectionalClient, error)
	ListBooks(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BookList, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/pb.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CreateBookStream(ctx context.Context, opts ...grpc.CallOption) (BookService_CreateBookStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[0], "/pb.BookService/CreateBookStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceCreateBookStreamClient{stream}
	return x, nil
}

type BookService_CreateBookStreamClient interface {
	Send(*CreateBookRequest) error
	CloseAndRecv() (*BookList, error)
	grpc.ClientStream
}

type bookServiceCreateBookStreamClient struct {
	grpc.ClientStream
}

func (x *bookServiceCreateBookStreamClient) Send(m *CreateBookRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bookServiceCreateBookStreamClient) CloseAndRecv() (*BookList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BookList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bookServiceClient) CreateBookStreamBidirectional(ctx context.Context, opts ...grpc.CallOption) (BookService_CreateBookStreamBidirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[1], "/pb.BookService/CreateBookStreamBidirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceCreateBookStreamBidirectionalClient{stream}
	return x, nil
}

type BookService_CreateBookStreamBidirectionalClient interface {
	Send(*CreateBookRequest) error
	Recv() (*Book, error)
	grpc.ClientStream
}

type bookServiceCreateBookStreamBidirectionalClient struct {
	grpc.ClientStream
}

func (x *bookServiceCreateBookStreamBidirectionalClient) Send(m *CreateBookRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bookServiceCreateBookStreamBidirectionalClient) Recv() (*Book, error) {
	m := new(Book)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bookServiceClient) ListBooks(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BookList, error) {
	out := new(BookList)
	err := c.cc.Invoke(ctx, "/pb.BookService/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/pb.BookService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	CreateBook(context.Context, *CreateBookRequest) (*Book, error)
	CreateBookStream(BookService_CreateBookStreamServer) error
	CreateBookStreamBidirectional(BookService_CreateBookStreamBidirectionalServer) error
	ListBooks(context.Context, *Blank) (*BookList, error)
	GetBook(context.Context, *GetBookRequest) (*Book, error)
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) CreateBook(context.Context, *CreateBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedBookServiceServer) CreateBookStream(BookService_CreateBookStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateBookStream not implemented")
}
func (UnimplementedBookServiceServer) CreateBookStreamBidirectional(BookService_CreateBookStreamBidirectionalServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateBookStreamBidirectional not implemented")
}
func (UnimplementedBookServiceServer) ListBooks(context.Context, *Blank) (*BookList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}
func (UnimplementedBookServiceServer) GetBook(context.Context, *GetBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_CreateBookStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BookServiceServer).CreateBookStream(&bookServiceCreateBookStreamServer{stream})
}

type BookService_CreateBookStreamServer interface {
	SendAndClose(*BookList) error
	Recv() (*CreateBookRequest, error)
	grpc.ServerStream
}

type bookServiceCreateBookStreamServer struct {
	grpc.ServerStream
}

func (x *bookServiceCreateBookStreamServer) SendAndClose(m *BookList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bookServiceCreateBookStreamServer) Recv() (*CreateBookRequest, error) {
	m := new(CreateBookRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BookService_CreateBookStreamBidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BookServiceServer).CreateBookStreamBidirectional(&bookServiceCreateBookStreamBidirectionalServer{stream})
}

type BookService_CreateBookStreamBidirectionalServer interface {
	Send(*Book) error
	Recv() (*CreateBookRequest, error)
	grpc.ServerStream
}

type bookServiceCreateBookStreamBidirectionalServer struct {
	grpc.ServerStream
}

func (x *bookServiceCreateBookStreamBidirectionalServer) Send(m *Book) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bookServiceCreateBookStreamBidirectionalServer) Recv() (*CreateBookRequest, error) {
	m := new(CreateBookRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BookService_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BookService/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ListBooks(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "ListBooks",
			Handler:    _BookService_ListBooks_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateBookStream",
			Handler:       _BookService_CreateBookStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateBookStreamBidirectional",
			Handler:       _BookService_CreateBookStreamBidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/book_author.proto",
}
